site_name: German Energy Forecast
repo_name: german-energy-forecast # Your GitHub repo name
repo_url: https://github.com/yourusername/german-energy-forecast # Your GitHub repo URL
edit_uri: "" # Removes the edit button
site_description: "A comprehensive guide to forecasting energy consumption in Germany"
theme:
  name: material
  icon:
    logo: material/home-analytics
  palette:
    scheme: slate
    primary: indigo
  features:
    #- navigation.tabs
    #- navigation.sections
    #- navigation.expand
    - navigation.left

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Dashboard: dashboard.md
  - Documentation:
      - API Reference: api.md
      - Models: models.md
  - Motivation: motivation.md
  - Data Ingestion: data_ingestion.md
  - EDA: eda.md
  - Feature Engineering: feature_engineering.md
  - Modelling: modelling.md
  - Industrialization: industrialization.md
  - Deployment: deployment.md
  - Conclusion: conclusion.md
  - About: about.md

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - footnotes
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - mkdocstrings:
      default_handler: python
  - glightbox
